-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 19:40:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app.tarefas.gf
-- -----------------------------------------------------
-- Trabalho desenvolvido por Gabriel Filippi.

-- -----------------------------------------------------
-- Schema app.tarefas.gf
--
-- Trabalho desenvolvido por Gabriel Filippi.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app.tarefas.gf` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `app.tarefas.gf` ;

-- -----------------------------------------------------
-- Table `app.tarefas.gf`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app.tarefas.gf`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `app.tarefas.gf`.`Usuario` (
  `idUsuario` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'id do usuario',
  `nomeUsuario` VARCHAR(65) NOT NULL COMMENT 'Nome do Usuario',
  `telefoneUsuario` VARCHAR(45) NOT NULL COMMENT 'telefone do Usuario',
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app.tarefas.gf`.`Tarefa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app.tarefas.gf`.`Tarefa` ;

CREATE TABLE IF NOT EXISTS `app.tarefas.gf`.`Tarefa` (
  `idTarefa` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'id da tarefa principal',
  `Usuario_idUsuario` INT(4) UNSIGNED ZEROFILL NOT NULL COMMENT 'Id Estrangeiro do usuario que pertence aquela tarefa',
  `nomeTarefa` VARCHAR(65) NOT NULL COMMENT 'nome da tarefa principal',
  `statusTarefa` TINYINT(1) UNSIGNED NOT NULL COMMENT 'Status da Tarefa onde, 1 =\"não realizado\"; 2 = \"realizado\"',
  `descricaoTarefa` TEXT NULL COMMENT 'descricao da tarefa principal',
  PRIMARY KEY (`idTarefa`),
  UNIQUE INDEX `idTarefa_UNIQUE` (`idTarefa` ASC),
  INDEX `fk_Tarefa_Usuario_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Tarefa_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `app.tarefas.gf`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app.tarefas.gf`.`Sub_Tarefa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app.tarefas.gf`.`Sub_Tarefa` ;

CREATE TABLE IF NOT EXISTS `app.tarefas.gf`.`Sub_Tarefa` (
  `idSub_Tarefa` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'id da sub tarefa',
  `Tarefa_idTarefa` INT(5) UNSIGNED ZEROFILL NOT NULL COMMENT 'id estrangeiro da Tarefa principal',
  `itemSubTarefa` TEXT NOT NULL COMMENT 'sub tarefa(item)',
  `statusSubTarefa` TINYINT(1) UNSIGNED NOT NULL COMMENT 'Status da sub tarefa onde, 1 =\"não realizado\"; 2 = \"realizado\"',
  PRIMARY KEY (`idSub_Tarefa`),
  UNIQUE INDEX `idItem_Tarefa_UNIQUE` (`idSub_Tarefa` ASC),
  INDEX `fk_Item_Tarefa_Tarefa1_idx` (`Tarefa_idTarefa` ASC),
  CONSTRAINT `fk_Item_Tarefa_Tarefa1`
    FOREIGN KEY (`Tarefa_idTarefa`)
    REFERENCES `app.tarefas.gf`.`Tarefa` (`idTarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
